
[target.'cfg(target_arch = "xtensa")']
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
]

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[build]
#target = "xtensa-esp32-none-elf"
# target = "xtensa-esp32s2-none-elf"
# target = "xtensa-esp32s3-none-elf"
#target = "riscv32imc-unknown-none-elf"
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = [ "core", "alloc" ]
