name: Run ESP32 CircuitPython examples and upload results to GitHub Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Upload to specific release"
        required: true
        default: 'v0.1.0'
      skip_projects:
        description: "Skip projects during build (e.g. esp32-c3-devkit-rust)"
        required: false
        default: ''

jobs:
  get_release:
    name: Get release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.get_upload_url.outputs.url }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get_release
        with:
          route: GET /repos/{owner}/{repo}/releases/tags/${{ github.event.inputs.release_tag }}
          owner: georgik
          repo: esp32-lang-lab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: get upload url
        id: get_upload_url
        run: |
          url=$(echo "$response" | jq -r '.upload_url' | sed 's/{?name,label}//')
          echo "url=$url" >> $GITHUB_OUTPUT
        env:
          response: ${{ steps.get_release.outputs.data }}

  build:
    runs-on: ubuntu-22.04
    # container:
    #   image: espressif/idf:release-v5.1
    needs: get_release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Wokwi CLI
        shell: bash
        run: |
          curl -L https://wokwi.com/ci/install.sh | sh
      - name: Install littlefs-python and esptool
        shell: bash
        run: |
          pip3 install littlefs-python esptool
      - name: Run tests and upload results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
        shell: bash
        run: |
          for TARGET in esp32 esp32s2 esp32s3 esp32c3 esp32c6 esp32h2; do
            ../tests/python/circuitpython/test-circuitpython.sh esp32c3 "`pwd`" "${{ github.event.inputs.release_tag }}" > "${PROJECT}/${OUTPUT_TXT}"

            # Upload log
            asset_path="${PROJECT}/${OUTPUT_TXT}"
            asset_name="${OUTPUT_TXT}"
            curl \
              --request POST \
              --header "authorization: Bearer $GITHUB_TOKEN" \
              --header "Content-Type: application/octet-stream" \
              --data-binary "@$asset_path" \
              --url "${{ needs.get_release.outputs.upload_url }}?name=${asset_name}"

            # Extract heap size (you might need to adjust the parsing command)
            HEAP_SIZE=$(grep 'Minimum free heap size' ${OUTPUT_TXT} | tr -d '\n' | sed -e 's/Minimum free heap size: //' -e 's/ bytes//')

            # Add a new record to the JSON database
            jq --arg target "$TARGET" \
                --arg language "Python" \
                --arg flavor "CircuitPython" \
                --arg example "hello-world" \
                --arg property "heap" \
                --arg value "$HEAP_SIZE" \
                --arg unit "bytes" \
                --arg note "" \
                --arg version "8.2.9" \
                --arg timestamp "$(date -Iseconds)" \
                '. += [{
                  target: $target,
                  language: $language,
                  flavor: $flavor,
                  example: $example,
                  property: $property,
                  value: $value,
                  unit: $unit,
                  note: $note,
                  version: $version,
                  timestamp: $timestamp
                }]' results.json > temp.json && mv temp.json results.json

          done

          # Generate report
          echo "| Target | Language | Flavor | Example | Property | Value | Unit | Note | Version | Timestamp |" > report.md
          echo "|--------|----------|--------|---------|----------|-------|------|------|---------|-----------|" >> report.md
          jq -r '.[] | "| \(.target) | \(.language) | \(.flavor) | \(.example) | \(.property) | \(.value) | \(.unit) | \(.note) | \(.version) | \(.timestamp) |"' results.json >> report.md

          asset_path="report.md"
          asset_name="python-circuitpython-hello-world-report.md"
          curl \
            --request POST \
            --header "authorization: Bearer $GITHUB_TOKEN" \
            --header "Content-Type: application/octet-stream" \
            --data-binary "@$asset_path" \
            --url "${{ needs.get_release.outputs.upload_url }}?name=${asset_name}"

          asset_path="results.json"
          asset_name="python-circuitpython-hello-world-results.json"
          curl \
            --request POST \
            --header "authorization: Bearer $GITHUB_TOKEN" \
            --header "Content-Type: application/octet-stream" \
            --data-binary "@$asset_path" \
            --url "${{ needs.get_release.outputs.upload_url }}?name=${asset_name}"
